baseurl = "https://calcoolstudios.com/"
title = "CalCool Studios"

# -------------------------
# Languages

defaultContentLanguage = 'fr'

[languages]
# Directives configurables par langue. La valeur globele est une valeur par défaut.
# baseURL buildDrafts buildExpired buildFuture canonifyURLs capitalizeListTitles contentDir copyright disableAliases
# disableHugoGeneratorInject disableKinds disableLiveReload disablePathToLower enableEmoji frontmatter hasCJKLanguage
# languageCode mainSections markup mediaTypes menus outputFormats outputs page pagination params permalinks
# pluralizeListTitles privacy refLinksErrorLevel refLinksNotFoundURL related relativeURLs removePathAccents
# renderSegments sectionPagesMenu security services sitemap staticDir summaryLength taxonomies timeZone title
# titleCaseStyle
  [languages.fr]
    disabled = false
    # Ordre
    weight = 0
    languageCode = 'fr-FR'
    languageDirection = 'ltr'
    languageName = 'Français'

disableLanguages = []

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "term"]

# -------------------------
# Modules
[module]
  [[module.imports]]
    path = 'github.com/dchucks/agnes-hugo-theme'

# Doit etre placé après la déclaration du module
theme = 'Agnes'

# -------------------------
[params]
  images = ["img/Logo v3-og-image-facebook.png"]
  dateFormat = "1 avril 2025"
  authorName = "CalCool Studios SAS"
#  google_analytics_id = "GA-"

# Home / Contacts / Products / Values
# Le menu se situe en bas à droite de la page Agnes.
[menu]
  [[menu.main]]
	Name = "Accueil"
	URL = "#top"
	weight = 1

  [[menu.main]]
	Name = "Contact"
	URL = "contact"
	weight = 2

  [[menu.main]]
	Name = "Produits"
	URL = "products"
	weight = 3

  [[menu.main]]
	Name = "Valeurs"
	URL = "values"
	weight = 4

  [[menu.main]]
    Name = "CGV"
    URL = "files/CGV_B2B.pdf"

[params.social]
	TwitterURL = "https://twitter.com/"
	GoogleURL = "http://google.com"
	FacebookURL = "https://facebook.com/podbharati"

[params.content]
	LeadTitle = "CalCool Studios"
	LeadDescription = "Our landing page template works for all the devices, so you only have to setup it once, and get beautiful results forever."
	ButtonCaption = "Prix et packages"
	ButtonURL = "#pricing"
################### Feature Columns (do not exceed 4) ####################

[[params.feature]]
	FeatureTitle = "Conseil et formation"
	FeatureDescription = "Nous vous aidons à sélectionner les technologies les plus adaptées à votre projet, celles qui rendront le meilleur service et peuvent etre déployées au coût le plus bas. Nous nous assurons que vos équipes ont acquis le savoir-faire nécessaire pour opérer les services en toute sécurité au cours d'une transition graduelle."
	FeatureImage = "images/feature-1.png"

[[params.feature]]
	FeatureTitle = "Coordination d'équipes"
	FeatureDescription = "Grace à notre connaissance des outils et des meilleures pratiques, nous participons à la sélection de votre équipe de développeurs et coordonnons leurs travaux."
	FeatureImage = "images/feature-2.png"

[[params.feature]]
	FeatureTitle = "Domaine et messagerie"
	FeatureDescription = "Nous trouvons le meilleur prestataire pour votre nom de domaine et configurons le DNS pour faire fonctionner tous vos services. Nous proposons un service de messagerie (e-mail) sécurisé pour vos adresses professionnelles et les services qui interagissent par e-mail."
	FeatureImage = "images/feature-3.png"

[[params.feature]]
	FeatureTitle = "Infrastructure"
	FeatureDescription = "Nous pouvons vous héberger sur nos serveurs ou configurer vos services dans le cloud. Sur nos serveurs vous pourrez mettre en place des agents IA alimentés par de grands modèles de langage."
	FeatureImage = "images/feature-4.png"

################### Pricing Columns (do not exceed 3) ####################

[[params.pricing]]
	PricingTitle = "Pour démarrer"
	PricingRate = "499"
	ButtonCaption = "En savoir plus"
 	ButtonURL = "consultations"
	[[params.pricing.Features]]
		Description = "Un mois pour auditer vos moyens et comprendre vos besoins"
	[[params.pricing.Features]]
		Description = "Une conférence audio par semaine"
	[[params.pricing.Features]]
		Description = "Un rapport de recommandations avec un devis"
	[[params.pricing.Features]]
		Description = "Une visite sur site en option"

[[params.pricing]]
	PricingTitle = "Votre domaine"
	PricingRate = "97"
	ButtonCaption = "En savoir plus"
 	ButtonURL = "domaine"
	[[params.pricing.Features]]
		Description = "Nom de domaine à prix coûtant"
	[[params.pricing.Features]]
		Description = "20 adresses mail professionnelles sur votre domaine"
	[[params.pricing.Features]]
		Description = "Un certificat SSL pour votre site web"
	[[params.pricing.Features]]
		Description = "Déploiement automatique de votre site web"

[[params.pricing]]
	PricingTitle = "Infrastructure"
	PricingRate = "A partir de 20"
	ButtonCaption = "En savoir plus"
 	ButtonURL = "infrastructure"
	[[params.pricing.Features]]
		Description = "Gestion des identités et des rôles"
	[[params.pricing.Features]]
		Description = "Hébergement de services back-end"
	[[params.pricing.Features]]
		Description = "Hébergement d'environnements de développement"
	[[params.pricing.Features]]
		Description = "Accès à un noeud de blockchain"
	[[params.pricing.Features]]
		Description = "Accès à un modèle IA local"
